package com.newsletter.newsletter.domain.dynamo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.newsletter.newsletter.domain.constants.CommonConstants;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

@DynamoDBTable(tableName = CommonConstants.TABLE_CLIENT)
@Setter
@Getter
@Builder
public class Client implements Serializable {

    private static final long serialVersionUID = -3534650012619938612L;

    private String clientId;
    private String name;
    private String email;
    private String telephone;

    @DynamoDBHashKey(attributeName = "clientId")
    @DynamoDBAutoGeneratedKey
    public String getClientId() {
        return clientId;
    }

}
